---

port: 3000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude:
  - .gitignore,
  - build_site.bash
  - README.md
  - test_site.bash
  - upload.bash
  - presentations
  - scripts
  
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "ROSCon China 2024"
keywords:    "ROSCon China 2024, robot, robotics, Robot Operating System, ROS"
description: "The annual ROS developer conference for X."
source_link: "http://localhost:3000"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-????????-?? ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  red:       '#EB2824'
  pink:      '#DA6365'
  light_pink: '#ECB3BA'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#4d235e'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  logo_green: '#7F9686'
  logo_orange: '#ED906E'
  logo_yellow: '#F5CA85'
  logo_purple: '#92468E'
  logo_purple2: '#542762'


# Output directory to match server directory
destination: '2024'
baseurl: '/2024'


# variables used throughout the site for consistency.
# also with an eye for avoiding copy and paste issues porting forward.
nth_roscon: 'twelveth'
roscon_year: '2024'
cfp_date: 'June 1, 2024'
diversity_application_deadline: 'May 15th, 2024'
workshop_submission_deadline: 'September 1, 2024'
submission_deadline: 'September 1, 2024'
acceptance_date: 'September 6th, 2024'
ticket_sales_begin: 'July 8th, 2024'
early_registration_deadline: 'September 15th, 2024'
late_registration_start: 'October 8th, 2024'
event_dates: 'November 1st to 3rd, 2024'
roscon_city: 'ShenZhen, China'
